#!/usr/bin/env bash
# =============================================================================
# discover.sh - Automatic server discovery
# Collects hardware, services, network and package information, detects
# workload profiles and generates config/generated/server-auto.yml
#
# Usage: sudo ./discover.sh [-o output.yml]
# =============================================================================
set -u

FRAMEWORK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FRAMEWORK_ROOT

# shellcheck source=lib/logging.sh
source "$FRAMEWORK_ROOT/lib/logging.sh"
# shellcheck source=lib/common.sh
source "$FRAMEWORK_ROOT/lib/common.sh"
# shellcheck source=lib/os_detect.sh
source "$FRAMEWORK_ROOT/lib/os_detect.sh"
# shellcheck source=lib/config_loader.sh
source "$FRAMEWORK_ROOT/lib/config_loader.sh"

INTERACTIVE=1
OUTPUT_FILE="$FRAMEWORK_ROOT/config/generated/server-auto.yml"

while getopts "o:h" opt; do
    case "$opt" in
        o) OUTPUT_FILE="$OPTARG" ;;
        h) grep '^#' "$0" | sed 's/^# \{0,2\}//'; exit 0 ;;
        *) echo "unknown option"; exit 1 ;;
    esac
done

[[ $EUID -eq 0 ]] || { echo "ERROR: run as root (sudo ./discover.sh)"; exit 1; }

logging_init
log_section "SERVER DISCOVERY"

os_detect || exit 1

# shellcheck disable=SC1091
source "$FRAMEWORK_ROOT/discovery/hardware.sh"
source "$FRAMEWORK_ROOT/discovery/services.sh"
source "$FRAMEWORK_ROOT/discovery/network.sh"
source "$FRAMEWORK_ROOT/discovery/packages.sh"

mkdir -p "$(dirname "$OUTPUT_FILE")"

# build firewall port suggestion from detected profiles
suggest_firewall_ports() {
    local ports=""
    [[ " ${DISCOVERED_PROFILES:-} " == *" web "* ]] && ports="80 443"
    if [[ " ${DISCOVERED_PROFILES:-} " == *" database "* ]]; then
        if [[ "$DISCOVERED_DB" == "postgresql" ]]; then ports="$ports 5432"; else ports="$ports 3306"; fi
    fi
    [[ " ${DISCOVERED_PROFILES:-} " == *" redis "* ]] && ports="$ports 6379"
    [[ " ${DISCOVERED_PROFILES:-} " == *" minio "* ]] && ports="$ports 9000 9001"
    echo "${ports# }"
}

{
    echo "# ============================================================="
    echo "# Auto-generated by nutbolt discover.sh"
    echo "# Host: $(hostname)    Date: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# Review and edit before using with install.sh --config"
    echo "# ============================================================="
    echo ""
    discovery_hardware
    echo ""
    discovery_network
    echo ""
    discovery_services
    echo ""
    discovery_packages "$(dirname "$OUTPUT_FILE")"
    echo ""
    echo "# ---- suggested profiles (review!) -------------------------------------"
    echo "profiles:"
    for p in web database redis minio docker; do
        if [[ " ${DISCOVERED_PROFILES:-} " == *" $p "* ]]; then
            echo "  $p:"
            echo "    enabled: true"
        else
            echo "  $p:"
            echo "    enabled: false"
        fi
    done
    echo ""
    echo "# ---- suggested firewall ports (review!) --------------------------------"
    echo "firewall:"
    echo "  enabled: true"
    echo "  tcp_ports: [$(suggest_firewall_ports | sed 's/ /, /g')]"
} > "$OUTPUT_FILE" 2>>"$LOG_FILE"

log_ok "Discovery complete: $OUTPUT_FILE"
log_info "Detected profiles: ${DISCOVERED_PROFILES:-none}"
log_info "Next steps:"
log_info "  1. Review the generated config"
log_info "  2. Run: sudo ./install.sh --config $OUTPUT_FILE"
log_info "     (or run interactive: sudo ./install.sh)"

exit 0
