#!/usr/bin/env bash
# =============================================================================
# generate-ansible.sh - Generate a ready-to-run Ansible project from the
# framework configuration (config/default.yml + config/servers/*.yml).
#
# Output:
#   ansible/inventory.ini
#   ansible/site.yml
#   ansible/group_vars/all.yml (+ per-profile group vars)
#   ansible/roles/{common,ssh,firewall,fail2ban,clamav,updates,sysctl,limits,
#                   docker,web,database,redis,minio}/
#
# Usage: ./generate-ansible.sh [-t target-dir] [-c config.yml]
# =============================================================================
set -u

FRAMEWORK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FRAMEWORK_ROOT

source "$FRAMEWORK_ROOT/lib/logging.sh"
source "$FRAMEWORK_ROOT/lib/common.sh"
source "$FRAMEWORK_ROOT/lib/os_detect.sh"
source "$FRAMEWORK_ROOT/lib/config_loader.sh"

TARGET="$FRAMEWORK_ROOT/ansible"
CONFIG_FILE=""

while getopts "t:c:h" opt; do
    case "$opt" in
        t) TARGET="$OPTARG" ;;
        c) CONFIG_FILE="$OPTARG" ;;
        h) grep '^#' "$0" | sed 's/^# \{0,2\}//'; exit 0 ;;
        *) exit 1 ;;
    esac
done

logging_init
log_section "GENERATING ANSIBLE PROJECT"

# config values drive group_vars defaults (framework runs on the control node,
# os_detect would fail here - do not call it)
OS_FAMILY="debian"

config_load_stack "$CONFIG_FILE"

SSH_PORT="$(config_get "ssh.port" 22222)"
SSH_MAXAUTH="$(config_get "ssh.max_auth_tries" 5)"
F2B_MAXRETRY="$(config_get "security.fail2ban.maxretry" 5)"
F2B_BANTIME="$(config_get "security.fail2ban.bantime" 1h)"
F2B_FINDTIME="$(config_get "security.fail2ban.findtime" 10m)"
NOFILE_DEFAULT="$(config_get "limits.nofile_default" 65535)"
NOFILE_DB="$(config_get "limits.nofile_database" 100000)"
NOFILE_MINIO="$(config_get "limits.nofile_minio" 200000)"
DOCKER_LOG_SIZE="$(config_get "profiles.docker.log_max_size" 10m)"
DOCKER_LOG_FILE="$(config_get "profiles.docker.log_max_file" 3)"

TCP_PORTS="$(config_get_list_csv "firewall.tcp_ports" "80 443")"
TCP_PORTS_YAML="$(config_get_list "firewall.tcp_ports" "80 443" | sed 's/^/      - /')"
UDP_PORTS_YAML="$(config_get_list "firewall.udp_ports" "" | sed 's/^/      - /')"
[[ -z "$UDP_PORTS_YAML" ]] && UDP_PORTS_YAML="      []"

mkdir -p "$TARGET"/{group_vars,host_vars}
ROLES="common ssh firewall fail2ban clamav updates sysctl limits docker web database redis minio"
for r in $ROLES; do
    mkdir -p "$TARGET/roles/$r/"{tasks,handlers,templates}
done

w() { # w <relative-path> ; content on stdin (overwrite)
    local f="$TARGET/$1"
    cat > "$f"
    log_ok "wrote: ansible/${1}"
}

# =============================================================================
# inventory.ini
# =============================================================================
w "inventory.ini" <<EOF
# =============================================================================
# Generated by nutbolt generate-ansible.sh
# Add your servers, then: ansible-playbook -i inventory.ini site.yml
# =============================================================================

[hardened:children]
web_servers
database_servers
redis_servers
minio_servers
docker_servers

[web_servers]
# web1.example.com ansible_host=203.0.113.10

[database_servers]
# db1.example.com ansible_host=203.0.113.20

[redis_servers]
# redis1.example.com ansible_host=203.0.113.30

[minio_servers]
# minio1.example.com ansible_host=203.0.113.40

[docker_servers]
# docker1.example.com ansible_host=203.0.113.50

[hardened:vars]
# ansible_user=admin
# ansible_ssh_port=$SSH_PORT
# ansible_become=true
EOF

# =============================================================================
# group_vars
# =============================================================================
w "group_vars/all.yml" <<EOF
# =============================================================================
# Global variables - generated from nutbolt configuration
# =============================================================================
ssh_port: $SSH_PORT
ssh_max_auth_tries: $SSH_MAXAUTH
ssh_disable_root_login: $(config_get ssh.disable_root_login true)
ssh_disable_password_auth: $(config_get ssh.disable_password_auth true)

firewall_enabled: $(config_get firewall.enabled true)
firewall_tcp_ports:
$TCP_PORTS_YAML
firewall_udp_ports:
$UDP_PORTS_YAML

security_fail2ban_enabled: $(config_get security.fail2ban.enabled true)
security_clamav_enabled: $(config_get security.clamav.enabled true)
security_updates_enabled: $(config_get security.updates.enabled true)
security_scan_exclude_defaults: $(config_get security.clamav.exclude_defaults true)

fail2ban_maxretry: $F2B_MAXRETRY
fail2ban_bantime: "$F2B_BANTIME"
fail2ban_findtime: "$F2B_FINDTIME"

limits_nofile_default: $NOFILE_DEFAULT
limits_nofile_database: $NOFILE_DB
limits_nofile_minio: $NOFILE_MINIO

docker_log_max_size: "$DOCKER_LOG_SIZE"
docker_log_max_file: "$DOCKER_LOG_FILE"

# profile switches (overridden per group)
profiles_web: false
profiles_database: false
profiles_redis: false
profiles_minio: false
profiles_docker: false
EOF

w "group_vars/web_servers.yml" <<'EOF'
profiles_web: true
EOF
w "group_vars/database_servers.yml" <<'EOF'
profiles_database: true
EOF
w "group_vars/redis_servers.yml" <<'EOF'
profiles_redis: true
EOF
w "group_vars/minio_servers.yml" <<'EOF'
profiles_minio: true
EOF
w "group_vars/docker_servers.yml" <<'EOF'
profiles_docker: true
EOF

w "host_vars/.gitkeep" </dev/null

# =============================================================================
# site.yml
# =============================================================================
w "site.yml" <<'EOF'
---
# =============================================================================
# nutbolt Ansible playbook
# Run: ansible-playbook -i inventory.ini site.yml
# =============================================================================
- name: Harden production Linux servers
  hosts: hardened
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: [common]

    - role: ssh
      tags: [ssh]

    - role: firewall
      when: firewall_enabled | bool
      tags: [firewall]

    - role: fail2ban
      when: security_fail2ban_enabled | bool
      tags: [fail2ban]

    - role: clamav
      when: security_clamav_enabled | bool
      tags: [clamav]

    - role: updates
      when: security_updates_enabled | bool
      tags: [updates]

    - role: sysctl
      tags: [sysctl]

    - role: limits
      tags: [limits]

    - role: web
      when: profiles_web | bool
      tags: [web]

    - role: database
      when: profiles_database | bool
      tags: [database]

    - role: redis
      when: profiles_redis | bool
      tags: [redis]

    - role: minio
      when: profiles_minio | bool
      tags: [minio]

    - role: docker
      when: profiles_docker | bool
      tags: [docker]

  post_tasks:
    - name: Remind about SSH port
      ansible.builtin.debug:
        msg: >
          SSH is configured on port {{ ssh_port }} - make sure it is open in the
          firewall and test login before closing your current session.
EOF

# =============================================================================
# roles: common
# =============================================================================
w "roles/common/tasks/main.yml" <<'EOF'
---
- name: Install base packages (Debian)
  ansible.builtin.apt:
    name: [sudo, curl, chrony]
    state: present
    update_cache: true
  when: ansible_facts.os_family == 'Debian'

- name: Install base packages (RHEL)
  ansible.builtin.dnf:
    name: [sudo, curl, chrony]
    state: present
  when: ansible_facts.os_family == 'RedHat'

- name: Enable EPEL (RHEL)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_facts.os_family == 'RedHat'
EOF

# =============================================================================
# roles: ssh
# =============================================================================
w "roles/ssh/tasks/main.yml" <<'EOF'
---
- name: Manage sshd options
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  loop:
    - { regexp: '^#?\\s*Port\\s+',                  line: 'Port {{ ssh_port }}' }
    - { regexp: '^#?\\s*MaxAuthTries\\s+',          line: 'MaxAuthTries {{ ssh_max_auth_tries }}' }
    - { regexp: '^#?\\s*PubkeyAuthentication\\s+',  line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?\\s*PermitRootLogin\\s+',       line: 'PermitRootLogin {{ "no" if ssh_disable_root_login | bool else "prohibit-password" }}' }
    - { regexp: '^#?\\s*PasswordAuthentication\\s+', line: 'PasswordAuthentication {{ "no" if ssh_disable_password_auth | bool else "yes" }}' }
    - { regexp: '^#?\\s*KbdInteractiveAuthentication\\s+', line: 'KbdInteractiveAuthentication {{ "no" if ssh_disable_password_auth | bool else "yes" }}' }
  notify: validate and restart sshd

# Port is additive in sshd_config - ensure no duplicate Port lines remain
- name: Remove duplicate Port directives
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '(?m)^(Port {{ ssh_port }}\n)(?:Port .*\n)+'
    replace: '\g<1>'
  notify: validate and restart sshd

- name: Disable ssh socket activation (custom port + service mode)
  ansible.builtin.systemd:
    name: ssh.socket
    enabled: false
    state: stopped
  ignore_errors: true
  when: ansible_facts.os_family == 'Debian'
  notify: validate and restart sshd
EOF

w "roles/ssh/handlers/main.yml" <<'EOF'
---
- name: validate and restart sshd
  block:
    - name: Validate sshd configuration
      ansible.builtin.command: /usr/sbin/sshd -t
      changed_when: false
    - name: Restart sshd
      ansible.builtin.systemd:
        name: "{{ 'ssh' if ansible_facts.os_family == 'Debian' else 'sshd' }}"
        state: restarted
EOF

# =============================================================================
# roles: firewall
# =============================================================================
w "roles/firewall/tasks/main.yml" <<'EOF'
---
- name: Configure firewall with UFW (Debian)
  when: ansible_facts.os_family == 'Debian'
  block:
    - name: Install ufw
      ansible.builtin.apt: { name: ufw, state: present }

    - name: Allow SSH port before enabling
      community.general.ufw: { rule: allow, port: "{{ ssh_port }}", proto: tcp }

    - name: Allow configured TCP ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ firewall_tcp_ports | default([]) }}"

    - name: Allow configured UDP ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: udp
      loop: "{{ firewall_udp_ports | default([]) | difference(['[]']) }}"

    - name: Set default policies
      community.general.ufw: { direction: incoming, policy: deny }

    - name: Set outgoing policy
      community.general.ufw: { direction: outgoing, policy: allow }

    - name: Enable ufw
      community.general.ufw: { state: enabled }

- name: Configure firewall with firewalld (RHEL)
  when: ansible_facts.os_family == 'RedHat'
  block:
    - name: Install firewalld
      ansible.builtin.dnf: { name: firewalld, state: present }

    - name: Start and enable firewalld
      ansible.builtin.systemd: { name: firewalld, state: started, enabled: true }

    - name: Allow SSH port
      ansible.posix.firewalld:
        port: "{{ ssh_port }}/tcp"
        permanent: true
        immediate: true
        state: enabled

    - name: Allow configured TCP ports
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ firewall_tcp_ports | default([]) }}"

    - name: Allow configured UDP ports
      ansible.posix.firewalld:
        port: "{{ item }}/udp"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ firewall_udp_ports | default([]) | difference(['[]']) }}"

    - name: Remove default ssh service (port 22) when port changed
      ansible.posix.firewalld:
        service: ssh
        permanent: true
        immediate: true
        state: "{{ 'disabled' if ssh_port | int != 22 else 'enabled' }}"
EOF

# =============================================================================
# roles: fail2ban
# =============================================================================
w "roles/fail2ban/tasks/main.yml" <<'EOF'
---
- name: Install fail2ban (Debian)
  ansible.builtin.apt: { name: fail2ban, state: present }
  when: ansible_facts.os_family == 'Debian'

- name: Install fail2ban (RHEL/EPEL)
  ansible.builtin.dnf: { name: fail2ban, state: present }
  when: ansible_facts.os_family == 'RedHat'

- name: Deploy fail2ban jail
  ansible.builtin.template:
    src: nutbolt.local.j2
    dest: /etc/fail2ban/jail.d/99-nutbolt.local
    mode: "0644"
  notify: restart fail2ban

- name: Enable and start fail2ban
  ansible.builtin.systemd: { name: fail2ban, state: started, enabled: true }
EOF

w "roles/fail2ban/handlers/main.yml" <<'EOF'
---
- name: restart fail2ban
  ansible.builtin.systemd: { name: fail2ban, state: restarted }
EOF

w "roles/fail2ban/templates/nutbolt.local.j2" <<'EOF'
# managed by nutbolt (ansible)
[DEFAULT]
bantime  = {{ fail2ban_bantime }}
findtime = {{ fail2ban_findtime }}
maxretry = {{ fail2ban_maxretry }}
{% if ansible_facts.os_family == 'RedHat' %}
banaction = firewallcmd-rich-rules
{% endif %}

[sshd]
enabled = true
port    = {{ ssh_port }}

{% if profiles_web | default(false) %}
[nginx-http-auth]
enabled = true
port    = http,https
logpath = /var/log/nginx/error.log

[apache-auth]
enabled = true
port    = http,https
logpath = /var/log/*error*.log
{% endif %}
EOF

# =============================================================================
# roles: clamav
# =============================================================================
w "roles/clamav/tasks/main.yml" <<'EOF'
---
- name: Install ClamAV (Debian)
  ansible.builtin.apt:
    name: [clamav, clamav-daemon, clamav-freshclam]
    state: present
  when: ansible_facts.os_family == 'Debian'

- name: Install ClamAV (RHEL)
  ansible.builtin.dnf:
    name: [clamav, clamav-update, clamd]
    state: present
  when: ansible_facts.os_family == 'RedHat'

- name: Enable freshclam (Debian)
  ansible.builtin.systemd: { name: clamav-freshclam, state: started, enabled: true }
  when: ansible_facts.os_family == 'Debian'

- name: Deploy security-scan command
  ansible.builtin.template:
    src: security-scan.j2
    dest: /usr/local/bin/security-scan
    mode: "0755"
EOF

w "roles/clamav/templates/security-scan.j2" <<'EOF'
#!/usr/bin/env bash
# security-scan - deployed by nutbolt (ansible)
# ClamAV scan with low CPU/IO priority. Exit: 0 clean, 1 infected, 2 error
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TARGET="${1:-/}"
SCAN_CMD=(clamscan)
command -v clamdscan >/dev/null 2>&1 && clamdscan --ping 2>/dev/null && SCAN_CMD=(clamscan --multiscan --fdpass)
{% if security_scan_exclude_defaults | default(true) %}
EXCLUDES=(--exclude-dir="^/var/lib/mysql" --exclude-dir="^/var/lib/postgresql" \
          --exclude-dir="^/var/lib/docker" --exclude-dir="^/var/lib/containerd" \
          --exclude-dir="^/var/lib/minio" --exclude-dir="^/mnt/minio" --exclude-dir="^/srv/minio" \
          --exclude-dir="^/var/lib/redis")
{% else %}
EXCLUDES=()
{% endif %}
nice -n 19 ionice -c3 "${SCAN_CMD[@]}" --infected --recursive "${EXCLUDES[@]}" "$TARGET"
rc=$?
case $rc in
    0) echo "RESULT: CLEAN"; exit 0 ;;
    1) echo "RESULT: INFECTED FILES FOUND"; exit 1 ;;
    *) echo "RESULT: ERROR (exit $rc)"; exit 2 ;;
esac
EOF

# =============================================================================
# roles: updates
# =============================================================================
w "roles/updates/tasks/main.yml" <<'EOF'
---
- name: Automatic updates (Debian)
  when: ansible_facts.os_family == 'Debian'
  block:
    - name: Install unattended-upgrades
      ansible.builtin.apt: { name: unattended-upgrades, state: present }

    - name: Enable auto upgrades
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::AutocleanInterval "7";

    - name: Security updates only - disable ${distro_codename}-updates origin
      ansible.builtin.replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '(?m)^(\s*)"?\$\{distro_id\}:\$\{distro_codename\}-updates"?\s*;'
        replace: '// removed by nutbolt (security-only)'

    - name: Never reboot automatically
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/51nutbolt-noreboot
        content: 'Unattended-Upgrade::Automatic-Reboot "false";'

- name: Automatic updates (RHEL)
  when: ansible_facts.os_family == 'RedHat'
  block:
    - name: Install dnf-automatic
      ansible.builtin.dnf: { name: dnf-automatic, state: present }

    - name: Security updates only
      ansible.builtin.lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^upgrade_type'
        line: 'upgrade_type = security'

    - name: Apply updates automatically
      ansible.builtin.lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^apply_updates'
        line: 'apply_updates = yes'

    - name: Enable dnf-automatic timer
      ansible.builtin.systemd: { name: dnf-automatic.timer, state: started, enabled: true }
EOF

# =============================================================================
# roles: sysctl
# =============================================================================
w "roles/sysctl/tasks/main.yml" <<'EOF'
---
- name: Deploy base hardening sysctl file
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-nutbolt.conf
    reload: true
  loop:
    - { name: net.ipv4.tcp_syncookies,             value: '1' }
    - { name: net.core.somaxconn,                  value: '65535' }
    - { name: fs.inotify.max_user_watches,         value: '524288' }
    - { name: net.ipv4.conf.all.accept_redirects,  value: '0' }
    - { name: net.ipv4.conf.default.accept_redirects, value: '0' }
    - { name: net.ipv6.conf.all.accept_redirects,  value: '0' }
    - { name: net.ipv6.conf.default.accept_redirects, value: '0' }
    - { name: net.ipv4.conf.all.send_redirects,    value: '0' }
    - { name: net.ipv4.conf.default.send_redirects, value: '0' }
    - { name: net.ipv4.conf.all.accept_source_route, value: '0' }
    - { name: net.ipv4.conf.default.accept_source_route, value: '0' }
    - { name: net.ipv6.conf.all.accept_source_route, value: '0' }
    - { name: net.ipv6.conf.default.accept_source_route, value: '0' }
    - { name: net.ipv4.conf.all.log_martians,      value: '1' }
EOF

# =============================================================================
# roles: limits
# =============================================================================
w "roles/limits/tasks/main.yml" <<'EOF'
---
- name: Deploy nofile limits
  ansible.builtin.copy:
    dest: /etc/security/limits.d/99-nutbolt.conf
    content: |
      # managed by nutbolt (ansible)
      *    soft nofile {{ limits_nofile_default }}
      *    hard nofile {{ limits_nofile_default }}
      root soft nofile {{ limits_nofile_default }}
      root hard nofile {{ limits_nofile_default }}
    mode: "0644"

- name: systemd LimitNOFILE override for detected services
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ item }}.d/99-nutbolt.conf"
    content: |
      [Service]
      LimitNOFILE={{ limits_nofile_default }}
    mode: "0644"
  loop: "{{ ['nginx', 'apache2', 'httpd', 'redis', 'redis-server', 'docker']
            | intersect(ansible_facts.services | default({}) | dict2items
            | map(attribute='key') | map('regex_replace', '\\.service$', '')
            | list) }}"
  notify: daemon reload
EOF

w "roles/limits/handlers/main.yml" <<'EOF'
---
- name: daemon reload
  ansible.builtin.systemd: { daemon_reload: true }
EOF

# =============================================================================
# roles: web / database / redis / minio (profile sysctl)
# =============================================================================
w "roles/web/tasks/main.yml" <<'EOF'
---
- name: Web profile sysctl tuning
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/98-profile-web.conf
    reload: true
  loop:
    - { name: net.ipv4.tcp_max_syn_backlog,       value: '65535' }
    - { name: net.core.netdev_max_backlog,        value: '16384' }
    - { name: net.ipv4.ip_local_port_range,       value: '10240 65535' }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: '0' }
EOF

w "roles/database/tasks/main.yml" <<'EOF'
---
- name: Database profile sysctl tuning
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/98-profile-database.conf
    reload: true
  loop:
    - { name: vm.swappiness,            value: '10' }
    - { name: vm.dirty_background_ratio, value: '10' }
    - { name: vm.dirty_ratio,           value: '20' }

- name: Database user nofile limits ({{ limits_nofile_database }})
  ansible.builtin.copy:
    dest: /etc/security/limits.d/99-nutbolt-database.conf
    content: |
      # managed by nutbolt (ansible)
      {% for u in ['mysql', 'postgres'] %}
      {{ u }} soft nofile {{ limits_nofile_database }}
      {{ u }} hard nofile {{ limits_nofile_database }}
      {% endfor %}
    mode: "0644"

- name: LimitNOFILE overrides for database services (applies on next restart)
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ item }}.d/99-nutbolt.conf"
    content: |
      [Service]
      LimitNOFILE={{ limits_nofile_database }}
    mode: "0644"
  loop: "{{ ['mariadb', 'mysqld', 'postgresql']
            | intersect(ansible_facts.services | default({}) | dict2items
            | map(attribute='key') | map('regex_replace', '\\.service$', '')
            | list) }}"
  notify: daemon reload
EOF

w "roles/database/handlers/main.yml" <<'EOF'
---
- name: daemon reload
  ansible.builtin.systemd: { daemon_reload: true }
EOF

w "roles/redis/tasks/main.yml" <<'EOF'
---
- name: Redis profile sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/98-profile-redis.conf
    reload: true
  loop:
    - { name: vm.overcommit_memory, value: '1' }
    - { name: net.core.somaxconn,   value: '65535' }

- name: Disable Transparent Huge Pages (unit)
  ansible.builtin.copy:
    dest: /etc/systemd/system/nutbolt-disable-thp.service
    content: |
      [Unit]
      Description=Disable Transparent Huge Pages (Redis recommendation)
      Before=redis.service redis-server.service multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Enable THP disable unit
  ansible.builtin.systemd: { name: nutbolt-disable-thp, enabled: true, state: started }
EOF

w "roles/minio/tasks/main.yml" <<'EOF'
---
- name: MinIO profile sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/98-profile-minio.conf
    reload: true
  loop:
    - { name: fs.aio-max-nr,             value: '1048576' }
    - { name: fs.file-max,               value: '2097152' }
    - { name: vm.dirty_background_ratio, value: '5' }
    - { name: vm.dirty_ratio,            value: '15' }

- name: MinIO nofile limits ({{ limits_nofile_minio }})
  ansible.builtin.copy:
    dest: /etc/security/limits.d/99-nutbolt-minio.conf
    content: |
      # managed by nutbolt (ansible)
      {% for u in ['minio', 'minio-user'] %}
      {{ u }} soft nofile {{ limits_nofile_minio }}
      {{ u }} hard nofile {{ limits_nofile_minio }}
      {% endfor %}
    mode: "0644"
EOF

# =============================================================================
# roles: docker
# =============================================================================
w "roles/docker/tasks/main.yml" <<'EOF'
---
- name: Install Docker (Debian)
  ansible.builtin.apt: { name: [docker.io, docker-compose-v2], state: present, update_cache: true }
  when: ansible_facts.os_family == 'Debian'

- name: Add Docker CE repository (RHEL)
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_facts.os_family == 'RedHat'

- name: Install Docker CE (RHEL)
  ansible.builtin.dnf:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
    state: present
  when: ansible_facts.os_family == 'RedHat'

- name: Deploy daemon.json (log rotation, live-restore; networking untouched)
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "{{ docker_log_max_size }}",
          "max-file": "{{ docker_log_max_file }}"
        },
        "live-restore": true
      }
    mode: "0644"
  notify: restart docker

- name: Enable and start Docker
  ansible.builtin.systemd: { name: docker, state: started, enabled: true }
EOF

w "roles/docker/handlers/main.yml" <<'EOF'
---
- name: restart docker
  ansible.builtin.systemd: { name: docker, state: restarted }
EOF

# =============================================================================
log_section "ANSIBLE PROJECT READY"
log_ok "Location: $TARGET"
log_info "Next steps:"
log_info "  1. Edit $TARGET/inventory.ini and add your servers"
log_info "  2. Review $TARGET/group_vars/all.yml"
log_info "  3. Install requirements: ansible-galaxy collection install community.general ansible.posix"
log_info "  4. Run: cd $TARGET && ansible-playbook -i inventory.ini site.yml"
exit 0
